### ISSUE TITLE
Add flag for random word

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/slng-node#26]
option syntax should be: `-R, --random`
Use endpoint: http://api.urbandictionary.com/v0/random

**Comment by rainrivas** [comment]
@jwu910 add the endpoint to the ticket

**Comment by jwu910** [comment]
@rainrivas Updated; Thanks.

**Comment by rainrivas** [comment]
Closing this out since I forgot we to do it when we merged 0.4.0
