### ISSUE TITLE
Add colored responses for readability

### ISSUE THREAD

**Issue by jwu910** [5-gwoap/slng-node#5]
Definition responses should have colored responses for better readability.

Styling should be similar to python verson:
![image](https://user-images.githubusercontent.com/12107969/34588428-ce8f1aaa-f161-11e7-8cae-0c721c06a742.png)

**Comment by jwu910** [comment]
```
Reset = "\x1b[0m"
Bright = "\x1b[1m"
Dim = "\x1b[2m"
Underscore = "\x1b[4m"
Blink = "\x1b[5m"
Reverse = "\x1b[7m"
Hidden = "\x1b[8m"

FgBlack = "\x1b[30m"
FgRed = "\x1b[31m"
FgGreen = "\x1b[32m"
FgYellow = "\x1b[33m"
FgBlue = "\x1b[34m"
FgMagenta = "\x1b[35m"
FgCyan = "\x1b[36m"
FgWhite = "\x1b[37m"

BgBlack = "\x1b[40m"
BgRed = "\x1b[41m"
BgGreen = "\x1b[42m"
BgYellow = "\x1b[43m"
BgBlue = "\x1b[44m"
BgMagenta = "\x1b[45m"
BgCyan = "\x1b[46m"
BgWhite = "\x1b[47m"
```
From : https://stackoverflow.com/questions/9781218/how-to-change-node-jss-console-font-color

**Comment by rainrivas** [comment]
@jwu910 we can use this... but how about we just use the packages we talked about, [npm chalk](https://www.npmjs.com/package/chalk) and [cli color](https://www.npmjs.com/package/cli-color)

**Comment by jwu910** [comment]
@rainrivas Oh yeah this was right before I found out we had packages available. I think the chalk package is pretty cool. I can get behind that.
