### ISSUE TITLE
When No Results Found, There is No Output

### ISSUE THREAD

**Issue by rainrivas** [5-gwoap/slng-node#7]
If a term yields no results, some sort of output should be given stating as much

**Comment by jwu910** [comment]
Maybe similar logic to https://github.com/5-gwoap/slng/blob/eb59711a450448bf23fce44efa85960e3d1dae91/slng#L40

**Comment by rainrivas** [comment]
> Maybe similar logic to https://github.com/5-gwoap/slng/blob/eb59711a450448bf23fce44efa85960e3d1dae91/slng#L40

@jwu910 Yes. Exactly like that. This would be extremely helpful.
